#!/bin/sh
rm log_stdout log_stderr
# exec 2>&1
set -e
seaf-cli start -c /home/ryan/.ccnet \
      >> log_stdout 2>> log_stderr
# Pause it because it is a oneshot
exec chpst -b seafile-client pause

## If you run the seafile-applet while this is running, it will take control of this daemon and restart all the sync processes.
## Closing the applet GUI does not end the process, that continues. If the process ends this service will not restart
## Make sure to restart the service with sv if you open the GUI and end that process.
