[main]
width=40        # Width in characters (default is 30)
lines=20        # Number of lines to display (default is 15)
font=FiraSans

[colors]
# Increased opacity to 92% (eb) for better legibility
background=282c34eb
# Clean, soft-white text
text=e1e1e1ff
# Dankshell violet (slightly more vibrant to stand out on the darker background)
match=bb93ffff
# Selection bar
selection=4a4458ff
# selection=4b5263ff
selection-text=ffffffff
selection-match=c6a0ffff
# Solid border for a cleaner outline
border=bb93ffff

[border]
width=3
