modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1.Browser ♖", "2.Term ♗", "3.Shell ♔", "4.Code ♕", "5", "6.Notes 📝", "7", "8.Messaging", "9", "10"]
# Comment out to use defaults
# layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
layout_mode = "Tag"
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

# See [https://github.com/leftwm/leftwm/wiki/Config#scratchpads](https://github.com/leftwm/leftwm/wiki/Config#scratchpads)
[[scratchpad]]
name = "Alacritty" # This is the name which is referenced when calling (case-sensitive)
value = "alacritty" # The command to load the application if it isn't started
# x, y, width, height are in pixels when an integer is inputted or a percentage when a float is inputted.
# These values are relative to the size of the workspace, and will be restricted depending on the workspace size.
x = 860
y = 390
height = 800
width = 1400

[[keybind]]
command = "ToggleScratchPad"
value = "Alacritty" # Name set for the scratchpad
modifier = ["modkey"]
key = "grave"

[[keybind]]
command = "ReturnToLastTag"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "FloatingToTile"
modifier = ["modkey", "Shift"]
key = "t"


[[keybind]]
command = "Execute"
value = "leftwm_change_theme.sh"
modifier = ["modkey"]
key = "a"


[[keybind]]
command = "Execute"
value = "rofi -location 2 -show drun lines 10 -eh 1 -mathing fuzzy -show-icons -window-thumbnail  -theme-str 'element-icon { size: 3ch;}' -theme DarkBlue"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "Execute"
value = "rofi -location 2 -show drun lines 10 -eh 1 -mathing fuzzy -show-icons -window-thumbnail  -theme-str 'element-icon { size: 3ch;}' -theme DarkBlue"
modifier = ["modkey"]
key = "space"


[[keybind]]
command = "Execute"
value = "rofi -show calc -modi calc -no-show-match -no-sort -theme DarkBlue"
modifier = ["modkey"]
key = "c"




[[keybind]]
command = "Execute"
value = "rofi -location 2 -show window lines 10 -eh 2 -mathing fuzzy -show-icons -window-thumbnail  -theme-str 'element-icon { size: 6ch; }' -theme DarkBlue"
modifier = ["modkey"]
key = "slash"

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "p"

# Open terminal (kitty is slow)
[[keybind]]
command = "Execute"
# value = "st" # keeps crashing
value = "alacritty" # Just works :shrug:
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "Execute"
value = "printf mem | sudo tee /sys/power/state"
modifier = ["modkey", "Shift"]
key = "BackSpace"


[[keybind]]
command = "CloseWindow"
value = ""
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
value = ""
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
value = ""
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
value = ""
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"




############################################################
### My Stuff ###############################################
############################################################


[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "RotateTag"
modifier = ["modkey"]
key = "z"

# *  Margin Multiplier
[[keybind]]
command = "SetMarginMultiplier"
value = "2.5"
modifier = ["modkey", "Control"]
key = "equal"


[[keybind]]
command = "SetMarginMultiplier"
value = "1"
modifier = ["modkey", "Control"]
key = "minus"

[[keybind]]
command = "SetMarginMultiplier"
value = "0"
modifier = ["modkey", "Control"]
key = "0"

# * Move Tags
# Tags are like desktops, workspaces are like monitors (good for ultrawides)
[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control", "Alt"]
key = "Left"

## * Layouts
[[keybind]]
command = "SetLayout"
value = "Fibonacci"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "SetLayout"
value = "Fibonacci"
modifier = ["modkey"]
key = "F1"

[[keybind]]
command = "SetLayout"
value = "MainAndDeck"
modifier = ["modkey"]
key = "F2"

[[keybind]]
command = "SetLayout"
value = "MainAndVertStack"
modifier = ["modkey"]
key = "F3"


[[keybind]]
command = "SetLayout"
value = "MainAndHorizontalStack"
modifier = ["modkey"]
key = "F4"

[[keybind]]
command = "SetLayout"
value = "CenterMain"
modifier = ["modkey"]
key = "F5"

[[keybind]]
command = "SetLayout"
value = "CenterMainBalanced"
modifier = ["modkey"]
key = "F6"

[[keybind]]
command = "SetLayout"
value = "GridHorizontal"
modifier = ["modkey"]
key = "F7"


[[keybind]]
command = "HardReload"
modifier = ["modkey", "Control"]
key = "r"

[[keybind]]
command = "Execute"
value = "maim --select | xclip -selection clipboard -target image/png"
modifier = ["modkey", "Shift"]
key = "s"

# Open jupyter and dokuwiki
[[keybind]]
command = "Execute"
# value = "dokuwiki_dmenu.sh"
value = "dash /home/ryan/.local/bin/dokuwiki_dmenu.sh"
modifier = ["modkey"]
key = "n"

[[keybind]]
command = "Execute"
# value = "dokuwiki_dmenu.sh"
value = "dash /home/ryan/.local/bin/jupyter_dmenu.sh"
modifier = ["modkey", "Shift"]
key = "n"
