#!/bin/sh
jupyter="$HOME/.local/share/virtualenvs/default/bin/jupyter"
notebooks="$HOME/Notes/Notebooks"

rm log_stdout log_stderr
exec  "${jupyter}" lab "${notebooks}" --port 8962 --no-browser \
    >> log_stdout 2>> log_stderr
