# ~/.config/i3/config
# ~/.config/i3status-rust/config.toml
# ~/.config/i3blocks/config

theme = "dracula"
icons = "awesome"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"


[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^5}"


[[block]]
block = "uptime"

[[block]]
block = "xrandr"
icons = true
resolution = false

# This causes slow down VVV
[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
on_click = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-yourusername/ | wofi --show dmenu"


# Need API key
#
# [[block]]
# block = "weather"
# format = "{weather} ({location}) {temp}, {wind} m/s {direction}"
# service = { name = "openweathermap", api_key = "XXX", city_id = "7281840", units = "metric" }


# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "Take a break!"
# break_message = "Back to work!"
# notifier = "swaynag"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
