general.import = ["/home/shai/.config/alacritty/themes/themes/citylights.toml"]

# [colors.bright]
# black = "#575b70"
# blue = "#caa9fa"
# cyan = "#9aedfe"
# green = "#5af78e"
# magenta = "#ff92d0"
# red = "#ff6e67"
# white = "#e6e6e6"
# yellow = "#f4f99d"
#
# [colors.normal]
# black = "#000000"
# blue = "#caa9fa"
# cyan = "#8be9fd"
# green = "#50fa7b"
# magenta = "#ff79c6"
# red = "#ff5555"
# white = "#bfbfbf"
# yellow = "#f1fa8c"
#
# [colors.primary]
# background = "#282a36"
# foreground = "#f8f8f2"

[font]
size = 10.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

